// Run with `casperjs --output-encoding=gbk login.js` to solve Chinese character issue

var casper = require('casper').create({
    verbose: true,
    logLevel: 'debug',
    pageSettings: {
        loadImages: false,
        loadPlugins: true,
        userAgent: 'Mozilla/5.0 (Windows NT 6.1; rv:17.0) Gecko/20100101 Firefox/17.0'
    }
});

casper.start('http://localhost:8080/login', function () {
    this.fill('form[action="/login"]', {
        username: "admin",
        password: "admin"
    }, true);
});

casper.thenOpen('http://localhost:8080/udr/page#!/create', function () {
//    this.click('.js-action-create-page');
});

casper.then(function () {
    this.fill("#page-angular-edit-form", { "thisEntity.title": 'casperjs', "thisEntity.content": "<div class='alert alert-info'>Content generated by casperjs</div>"}, false);
//    this.evaluate(function(){document.querySelector('.js-action-save-edit').click()});
    this.click('.js-action-save-edit');
//    this.echo(this.getHTML());

//    this.onResourceRequested(function(reqeust){
//        this.echo("SENDING REQUEST #" + request.id + " TO " + request.url, "PARAMETER");
//        this.echo(JSON.stringify(request, null, 4));
//    });
});
//casper.thenClick(".js-action-save-edit");

//casper.options.onResourceRequested = function(C, requestData, request) {
//    console.log(JSON.stringify(requestData));
//};
//casper.options.onResourceReceived = function(C, response) {
//    console.log(response.headers);
//};

casper.on('resource.requested', function (request) {
    if (request.url.indexOf('udr/page/create_do.json') > 0) {
        this.echo("SENDING REQUEST #" + request.id + " TO " + request.url, "PARAMETER");
        this.echo(JSON.stringify(request, null, 4));
    }
});

casper.run(function () {
    this.echo('测试结束').exit();
});
